---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  ports:
    - name: gitlab-ui
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
    # - name: gitlab-ui-https
    #   port: 443
    #   protocol: TCP
    #   targetPort: 443
    #   nodePort: 30443
    - name: gitlab-ssh
      port: 22
      protocol: TCP
      targetPort: 22
      nodePort: 30022
  selector:
    app: gitlab
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-claim
  labels:
    app: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
        tier: frontend
    spec:
      containers:
        - image: gitlab/gitlab-ce:10.7.3-ce.0
          name: gitlab
          env:
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                postgresql['enable'] = false
                gitlab_rails['db_username'] = "gitlab"
                gitlab_rails['db_password'] = "gitlab"
                gitlab_rails['db_host'] = "postgresql"
                gitlab_rails['db_port'] = "5432"
                gitlab_rails['db_database'] = "gitlabhq_production"
                gitlab_rails['db_adapter'] = 'postgresql'
                gitlab_rails['db_encoding'] = 'utf8'
                redis['enable'] = false
                gitlab_rails['redis_host'] = 'redis'
                gitlab_rails['redis_port'] = '6379'
                gitlab_rails['gitlab_shell_ssh_port'] = 22
                nginx['listen_port'] = 80
                nginx['listen_https'] = false
                external_url 'https://gitlab-staging-demo.us-south.containers.mybluemix.net'
          ports:
            - containerPort: 80
              name: gitlab
            # - containerPort: 443
            #   name: gitlab-https
            - containerPort: 22
              name: gitlab-ssh
          volumeMounts:
            - name: gitlab
              mountPath: /var/opt/gitlab
              subPath: gitlab_data
            - name: gitlab
              mountPath: /etc/gitlab
              subPath: gitlab_configuration
            # - name: certificates
            #   mountPath: /etc/gitlab/ssl
            #   readOnly: true
      volumes:
        - name: gitlab
          persistentVolumeClaim:
            claimName: gitlab-claim
        # - name: certificates
        #   secret:
        #     secretName: gitlab-staging-demo
        #     items:
        #       - key: tls.crt
        #         path: gitlab-staging-demo.us-south.containers.mybluemix.net.crt
        #       - key: tls.key
        #         path: gitlab-staging-demo.us-south.containers.mybluemix.net.key
